[package]
name = "redis-keyspace-stats"
version = "0.1.0"
authors = ["Scott Hardy <scott.the.hardy@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
glob = "0.3.0"
humantime = "2.0.1"
pretty-bytes = "0.2.2"
prettytable-rs = "0.8.0"
rand = "0.7.3"

[dependencies.redis]
version = "0.17.0"
features = ["tokio-comp", "tls", "tokio-tls-comp", "async-std-tls-comp"]
